/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class PromptTemplate {
  constructor(template: string, variables: Array<string>)
  format(values: Record<string, string>): string
}
export type SambaNovaLLM = SambaNovaLlm
export declare class SambaNovaLlm {
  constructor(model: string, apiKey?: string | undefined | null, systemPrompt?: string | undefined | null, temperature?: number | undefined | null, maxTokens?: number | undefined | null, topK?: number | undefined | null, topP?: number | undefined | null)
}
export declare class Chain {
  constructor(prompt: PromptTemplate, llm: SambaNovaLlm)
  invoke(inputs: Record<string, string>): Promise<string>
}
