/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AgentExecutor {
  constructor(llmInput: SambaNovaLLM | OpenAILLM | AnthropicLLM | GoogleGenAILLM | OllamaLLM)
  execute(input: string): Promise<string>
}

export declare class AnthropicLLM {
  constructor(apiKey: string, model: string, systemPrompt?: string | undefined | null, maxTokens?: number | undefined | null)
}

export declare class Chain {
  constructor(prompt: PromptTemplate, llmInput: SambaNovaLLM | OpenAILLM | AnthropicLLM | GoogleGenAILLM | OllamaLLM, memory?: ConversationBufferMemory | undefined | null)
  invoke(inputs: Record<string, string>): Promise<string>
}

export declare class ConversationBufferMemory {
  constructor()
}

export declare class Document {
  constructor(pageContent: string, metadata?: Record<string, string> | undefined | null)
  get pageContent(): string
  get metadata(): Record<string, string>
}

export declare class GoogleGenAILLM {
  constructor(apiKey: string, model: string, temperature?: number | undefined | null, maxTokens?: number | undefined | null)
}

export declare class InMemoryVectorStore {
  constructor(embeddings: MockEmbeddings)
  addDocuments(docs: Array<Document>): Promise<Array<string>>
  similaritySearch(query: string, k: number): Promise<Array<Document>>
}

export declare class MockEmbeddings {
  constructor()
  embedQuery(text: string): Promise<Array<number>>
}

export declare class OllamaLLM {
  constructor(model: string, baseUrl?: string | undefined | null, temperature?: number | undefined | null)
}

export declare class OpenAILLM {
  constructor(apiKey: string, model: string, baseUrl?: string | undefined | null, systemPrompt?: string | undefined | null, temperature?: number | undefined | null, maxTokens?: number | undefined | null)
}

export declare class PromptTemplate {
  constructor(template: string, variables: Array<string>)
  format(values: Record<string, string>): string
}

export declare class SambaNovaLLM {
  constructor(model: string, apiKey?: string | undefined | null, systemPrompt?: string | undefined | null, temperature?: number | undefined | null, maxTokens?: number | undefined | null, topK?: number | undefined | null, topP?: number | undefined | null)
}

export declare class TextLoader {
  constructor(filePath: string)
  load(): Array<Document>
}
